config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  # get 'gossips/index'
  # get 'gossips/show'
  # get 'pages/home'
  # get 'pages/team'
  # get 'pages/contact'
  # get 'pages/welcome'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'pages#home'
  get 'team', to: 'pages#team'
  get 'contact', to: 'pages#contact'
  get 'welcome/:first_name', to: 'pages#welcome', as: 'welcome'
  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  
  resources :users, only: [:show]
  resources :cities, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags

  validates :title, presence: true
  validates :content, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender
  belongs_to :receiver
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'
  has_many :received_messages, class_name: 'Message', foreign_key: 'receiver_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
    @gossips = @city.users.map(&:gossips).flatten
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.new(comment_params)
    @comment.user = User.first # Remplacer par l'utilisateur actuel

    if @comment.save
      redirect_to @gossip, notice: 'Commentaire ajouté avec succès.'
    else
      redirect_to @gossip, alert: 'Erreur lors de l\'ajout du commentaire.'
    end
  end

  def edit
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.find(params[:id])

    if @comment.update(comment_params)
      redirect_to @gossip, notice: 'Commentaire mis à jour avec succès.'
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.find(params[:id])
    @comment.destroy
    redirect_to '/gossips', notice: 'Commentaire supprimé avec succès.'
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new
    @comments = @gossip.comments
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)
    if @gossip.save
      redirect_to @gossip, notice: 'Potin créé avec succès.'
    else
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(gossip_params)
      redirect_to @gossip, notice: 'Potin mis à jour avec succès.'
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to @gossip, notice: 'Potin supprimé avec succès.'
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content, :author_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @gossips = Gossip.all
  end

  def team

  end

  def contact

  end

  def welcome
      @first_name = params[:first_name]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<h1>Ville de <%= @city.name %></h1>
<h2>Potins de cette ville :</h2>
<ul>
  <% @gossips.each do |gossip| %>
    <li><%= link_to gossip.title, gossip_path(gossip) %> par <%= link_to gossip.author.first_name, user_path(gossip.author) %></li>
  <% end %>
</ul>
<%= link_to 'Retour', root_path, class: 'btn btn-secondary' %>

app/views/comments/edit.html.erb
<h1>Modifier Commentaire</h1>
<%= form_with model: [ @gossip, @comment ], local: true do |form| %>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>
  <%= form.submit 'Modifier Commentaire', class: 'btn btn-primary' %>
<% end %>
<%= link_to 'Retour', gossip_path(@gossip), class: 'btn btn-secondary' %>

app/views/comments/form.html.erb
<%= form_with model: [ @gossip, @comment ], local: true do |form| %>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>
  <%= form.submit 'Ajouter Commentaire', class: 'btn btn-primary' %>
<% end %>

app/views/gossips/edit.html.erb
<h1>Modifier Potin</h1>
<%= form_with model: @gossip, local: true do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>
  <%= form.submit 'Mettre à jour', class: 'btn btn-primary' %>
<% end %>
<%= link_to 'Retour', root_path, class: 'btn btn-secondary' %>

app/views/gossips/gossip.html.erb
<div class="card">
  <div class="card-head">
    <%= link_to gossip.title, gossip_path(gossip) %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= link_to gossip.title, gossip_path(gossip) %></h5>
    <p class="card-text">Contenu : <%= @gossip.content %></p>
    <p>Auteur : <%= link_to @gossip.author.first_name, user_path(@gossip.author) %></p>
    <p>Ville de l'auteur : <%= link_to @gossip.author.city.name, city_path(@gossip.author.city) %></p>
    <%= link_to 'Modifier', edit_gossip_path(@gossip), class: 'btn btn-warning' %>
    <%= link_to 'Supprimer', @gossip, method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, class: 'btn btn-danger' %>
    <%= link_to 'Retour', root_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/gossips/index.html.erb
<div class="container">
<h1>Bienvenue sur The Big Project</h1>

  <div class="row">
    <% @gossips.each do |gossip| %>
      <div class="col-md-6 col-lg-3 my-2">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= link_to gossip.title, gossip_path(gossip) %></h5>
            <p class="card-text">Par <%= link_to gossip.user.first_name, user_path(gossip.user) %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/gossips/list.html.erb
<%= @gossips.each do |gossip| %>
  <%= render gossip %>
<% end %>

app/views/gossips/new.html.erb
<h1>Nouveau Potin</h1>
<%= form_with model: @gossip, local: true do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :author_id %>
    <%= form.number_field :author_id, class: 'form-control' %>
  </div>
  <%= form.submit 'Créer Potin', class: 'btn btn-primary' %>
<% end %>
<%= link_to 'Retour', root_path, class: 'btn btn-secondary' %>

app/views/gossips/show.html.erb
<div class="container my-3">
<div class="card">
  <div class="card-head">
    <%= link_to @gossip.title, gossip_path(@gossip) %>
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= link_to @gossip.title, gossip_path(@gossip) %></h5>
    <p class="card-text">Contenu : <%= @gossip.content %></p>
    <p>Auteur : <%= link_to @gossip.user.first_name, user_path(@gossip.user) %> <br>
      Date de publication : <%= @gossip.created_at.strftime('%d/%m/%Y') %>
    </p>
    <p>Ville de l'auteur : <%= link_to @gossip.user.city.name, city_path(@gossip.user.city) %></p>
    <%= link_to 'Modifier', edit_gossip_path(@gossip), class: 'btn btn-warning' %>
    <%= link_to 'Supprimer', gossip_path(@gossip), method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, class: 'btn btn-danger' %>
    <%= link_to 'Retour', root_path, class: 'btn btn-secondary' %>
  </div>
</div>

<h2>Commentaires</h2>
<ul>
  <% @gossip.comments.each do |comment| %>
    <li>
      <%= comment.content %>
      <%= link_to 'Modifier', edit_gossip_comment_path(@gossip, comment), class: 'btn btn-warning btn-sm' %>
      <%= link_to 'Supprimer', gossip_comment_path(@gossip, comment), method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: 'Are you sure?' } %>
    </li>
  <% end %>
</ul>

<h3>Ajouter un commentaire</h3>
<%= form_with model: [ @gossip, @comment ], local: true do |form| %>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>
  <%= form.submit 'Ajouter Commentaire', class: 'btn btn-primary' %>
<% end %>

</div>

app/views/users/show.html.erb
<h1>Profil de <%= @user.first_name %> <%= @user.last_name %></h1>
<p>Email: <%= @user.email %></p>

<h1>Profil de <%= @user.first_name %> <%= @user.last_name %></h1>
<p>Prénom : <%= @user.first_name %></p>
<p>Nom : <%= @user.last_name %></p>
<p>Description : <%= @user.description %></p>
<p>Email : <%= @user.email %></p>
<p>Âge : <%= @user.age %></p>
<p>Ville : <%= link_to @user.city.name, city_path(@user.city) %></p>
<%= link_to 'Retour', root_path, class: 'btn btn-secondary' %>