config/routes.rb
Rails.application.routes.draw do
  # get 'users/show'
  # get 'gossips/index'
  # get 'gossips/show'
  # get 'pages/home'
  # get 'pages/team'
  # get 'pages/contact'
  # get 'pages/welcome'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'pages#home'
  get 'team', to: 'pages#team'
  get 'contact', to: 'pages#contact'
  get 'welcome/:first_name', to: 'pages#welcome', as: 'welcome'
  resources :gossips do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  
  resources :users, only: [:show]
  resources :cities, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validates :content, presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :likes
  has_many :gossip_tags
  has_many :tags, through: :gossip_tags

  validates :title, presence: true
  validates :content, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender
  belongs_to :receiver
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :gossip_tags
  has_many :gossips, through: :gossip_tags
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :likes
  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'
  has_many :received_messages, class_name: 'Message', foreign_key: 'receiver_id'
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
    @gossips = @city.users.map(&:gossips).flatten
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.new(comment_params)
    @comment.user = User.first # Remplacer par l'utilisateur actuel

    if @comment.save
      redirect_to @gossip, notice: 'Commentaire ajouté avec succès.'
    else
      redirect_to @gossip, alert: 'Erreur lors de l\'ajout du commentaire.'
    end
  end

  def edit
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.find(params[:id])

    if @comment.update(comment_params)
      redirect_to @gossip, notice: 'Commentaire mis à jour avec succès.'
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    @comment = @gossip.comments.find(params[:id])
    @comment.destroy
    redirect_to '/gossips', notice: 'Commentaire supprimé avec succès.'
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
    @comment = Comment.new
    @comments = @gossip.comments
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(gossip_params)
    if @gossip.save
      redirect_to @gossip, notice: 'Potin créé avec succès.'
    else
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(gossip_params)
      redirect_to @gossip, notice: 'Potin mis à jour avec succès.'
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to @gossip, notice: 'Potin supprimé avec succès.'
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content, :author_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @gossips = Gossip.all
  end

  def team

  end

  def contact

  end

  def welcome
      @first_name = params[:first_name]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheBigProjet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">The Big Project</a>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <%= link_to 'Accueil', root_path, class: 'nav-link' %>
          </li>
        <li class="nav-item">
          <%= link_to 'Team', team_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact', contact_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
    <%= yield %>
  </body>
</html>

app/views/pages/contact.html.erb
<h1>Contactez-nous</h1>
<p>Superbe adresse de contact : contact@bigproject.com</p>

app/views/pages/home.html.erb
<div class="container">
<h1>Bienvenue sur The Big Project</h1>

  <div class="row">
    <% @gossips.each do |gossip| %>
      <div class="col-md-6 col-lg-3 my-2">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= link_to gossip.title, gossip_path(gossip) %></h5>
            <p class="card-text">Par <%= link_to gossip.user.first_name, user_path(gossip.user) %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/pages/team.html.erb
<h1>Notre Équipe</h1>
<p>Voici notre équipe lol mdr ❤</p>

app/views/pages/welcome.html.erb
<h1>Bienvenue <%= params[:first_name] %>!</h1>
<p>Ici c'est notre super site de potins, il est chouette, non ?</p>